<a href="https://colab.research.google.com/github/AroopGit/ML_Projects/blob/main/Fake_News_Detector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
fake=pd.read_csv("/content/Fake.csv")

In [ ]:
true=pd.read_csv("/content/True.csv")

In [ ]:
true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [ ]:
fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [ ]:
fake['label']=0

In [ ]:
true['label']=1

In [ ]:
true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  label  
0  December 31, 2017       1  
1  December 29, 2017       1  
2  December 31, 2017       1  
3  December 30, 2017       1  
4  December 29, 2017       1

In [ ]:
news=pd.concat([true, fake], axis=0)

In [ ]:
news

title  \
0      As U.S. budget fight looms, Republicans flip t...   
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text       subject  \
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2      WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3      WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4      SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
...                                                  ...           ...   
23476  21st Century Wire says As 21WIRE reported earl...   Middle-east   
23477  21st Century Wire says It s a familiar theme. ...   Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...   Middle-east   
23479  21st Century Wire says Al Jazeera America will...   Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...   Middle-east   

                     date  label  
0      December 31, 2017       1  
1      December 29, 2017       1  
2      December 31, 2017       1  
3      December 30, 2017       1  
4      December 29, 2017       1  
...                   ...    ...  
23476    January 16, 2016      0  
23477    January 16, 2016      0  
23478    January 15, 2016      0  
23479    January 14, 2016      0  
23480    January 12, 2016      0  

[44898 rows x 5 columns]

n

In [ ]:
news = news[['text', 'label']]

In [ ]:
news

text  label
0      WASHINGTON (Reuters) - The head of a conservat...      1
1      WASHINGTON (Reuters) - Transgender people will...      1
2      WASHINGTON (Reuters) - The special counsel inv...      1
3      WASHINGTON (Reuters) - Trump campaign adviser ...      1
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      1
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      0
23477  21st Century Wire says It s a familiar theme. ...      0
23478  Patrick Henningsen  21st Century WireRemember ...      0
23479  21st Century Wire says Al Jazeera America will...      0
23480  21st Century Wire says As 21WIRE predicted in ...      0

[44898 rows x 2 columns]

In [ ]:
news=news.sample(frac=1)

In [ ]:
news

text  label
6666   Comedian and actor Will Ferrell has been cast ...      0
9536   After months of lying about passing debate que...      0
10281  WASHINGTON (Reuters) - House Speaker Paul Ryan...      1
12098  SEOUL (Reuters) - South Korea s foreign minist...      1
5550   Newly released video shows a group of Texas in...      0
...                                                  ...    ...
4586   WASHINGTON (Reuters) - The White House has inv...      1
21745  The EPA must be really bored with the importan...      0
7394   BRUSSELS (Reuters) - NATO promised on Wednesda...      1
8149   There s this longstanding myth that s been spr...      0
17153  ISTANBUL (Reuters) - Turkey s talks with the U...      1

[44898 rows x 2 columns]

In [ ]:
#we need to sort the mixed indexes

In [ ]:


news = news.sort_index()


In [ ]:
news

text  label
0      Donald Trump just couldn t wish all Americans ...      0
0      WASHINGTON (Reuters) - The head of a conservat...      1
1      House Intelligence Committee Chairman Devin Nu...      0
1      WASHINGTON (Reuters) - Transgender people will...      1
2      On Friday, it was revealed that former Milwauk...      0
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      0
23477  21st Century Wire says It s a familiar theme. ...      0
23478  Patrick Henningsen  21st Century WireRemember ...      0
23479  21st Century Wire says Al Jazeera America will...      0
23480  21st Century Wire says As 21WIRE predicted in ...      0

[44898 rows x 2 columns]

In [ ]:


news.reset_index(drop=True, inplace=True)


In [ ]:
import re

In [ ]:

def wordopt(text):
  #to convert words into lowercase
  text=text.lower()
  #to remove URLs
  text = re.sub(r'http\S+', '', text)
  #to remove HTML tags
  text = re.sub(r'<.*?>', '', text)
  #to remove punctuation
  text = re.sub(r'[^\w\s]', '', text)
  #to remove digits
  text = re.sub(r'\d', '', text)
  #to remove newline characters
  text = re.sub(r'\n', '', text)

  return text


In [ ]:
news['text']=news['text'].apply(wordopt)

In [ ]:
news

text  label
0      donald trump just couldn t wish all americans ...      0
1      washington reuters  the head of a conservative...      1
2      house intelligence committee chairman devin nu...      0
3      washington reuters  transgender people will be...      1
4      on friday it was revealed that former milwauke...      0
...                                                  ...    ...
44893  st century wire says as wire reported earlier ...      0
44894  st century wire says it s a familiar theme whe...      0
44895  patrick henningsen  st century wireremember wh...      0
44896  st century wire says al jazeera america will g...      0
44897  st century wire says as wire predicted in its ...      0

[44898 rows x 2 columns]

In [ ]:
X=news['text']
Y=news['label']

In [ ]:
X

0        donald trump just couldn t wish all americans ...
1        washington reuters  the head of a conservative...
2        house intelligence committee chairman devin nu...
3        washington reuters  transgender people will be...
4        on friday it was revealed that former milwauke...
                               ...                        
44893    st century wire says as wire reported earlier ...
44894    st century wire says it s a familiar theme whe...
44895    patrick henningsen  st century wireremember wh...
44896    st century wire says al jazeera america will g...
44897    st century wire says as wire predicted in its ...
Name: text, Length: 44898, dtype: object

In [ ]:
Y


0        0
1        1
2        0
3        1
4        0
        ..
44893    0
44894    0
44895    0
44896    0
44897    0
Name: label, Length: 44898, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2)

In [ ]:


from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)


In [ ]:


from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

model = LogisticRegression()
model.fit(X_train_vect, Y_train)
y_pred = model.predict(X_test_vect)

print(classification_report(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4717
           1       0.99      0.99      0.99      4263

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

[[4659   58]
 [  40 4223]]


In [ ]:


from sklearn.tree import DecisionTreeClassifier

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Vectorize the text data
vectorizer = TfidfVectorizer()
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

# Train the decision tree classifier model
model = DecisionTreeClassifier()
model.fit(X_train_vect, Y_train)

# Make predictions on the test data
y_pred = model.predict(X_test_vect)

# Evaluate the model
print(classification_report(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4690
           1       1.00      1.00      1.00      4290

    accuracy                           1.00      8980
   macro avg       1.00      1.00      1.00      8980
weighted avg       1.00      1.00      1.00      8980

[[4680   10]
 [  18 4272]]


In [ ]:


from sklearn.ensemble import RandomForestClassifier

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Vectorize the text data
vectorizer = TfidfVectorizer()
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

# Train the random forest classifier model
model = RandomForestClassifier()
model.fit(X_train_vect, Y_train)

# Make predictions on the test data
y_pred = model.predict(X_test_vect)

# Evaluate the model
print(classification_report(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4753
           1       0.99      0.99      0.99      4227

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

[[4704   49]
 [  26 4201]]


In [ ]:


from sklearn.ensemble import GradientBoostingClassifier

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Vectorize the text data
vectorizer = TfidfVectorizer()
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

# Train the gradient boosting classifier model
model = GradientBoostingClassifier()
model.fit(X_train_vect, Y_train)

# Make predictions on the test data
y_pred = model.predict(X_test_vect)

# Evaluate the model
print(classification_report(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      0.99      1.00      4713
           1       0.99      1.00      1.00      4267

    accuracy                           1.00      8980
   macro avg       1.00      1.00      1.00      8980
weighted avg       1.00      1.00      1.00      8980

[[4688   25]
 [  10 4257]]


In [ ]:


def output_label(text):
  text = wordopt(text)
  vectorized_text = vectorizer.transform([text])
  prediction = model.predict(vectorized_text)
  if prediction == 0:
    return "Fake News"
  else:
    return "True News"


In [ ]:


def manual_testing():
  """
  This function allows you to manually test the model by inputting a news article.
  """

  # Get the news article from the user
  news_article = input("Enter a news article: ")

  # Preprocess the news article
  preprocessed_article = wordopt(news_article)

  # Vectorize the preprocessed article
  vectorized_article = vectorizer.transform([preprocessed_article])

  # Make a prediction on the vectorized article
  prediction = model.predict(vectorized_article)

  # Print the prediction
  if prediction == 0:
    print("Fake News")
  else:
    print("True News")

# Call the manual testing function
manual_testing()


Enter a news article: BREAKING: Popular Streaming Service Announces Users Can Now Earn Crypto While Watching
Fake News
